services:
  db:
    image: mariadb:11.8.3
    container_name: events_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: dev_user
      MARIADB_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - ./init-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
