name: ETL Continuous Integration

# 1. 언제 실행할 것인가?
on:
  push:
    branches: [ "feature/cicd" ] # 지금 작업 중인 브랜치

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub이 빌드용 컴퓨터를 한 대 빌려줍니다.

    steps:
      # 2. 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. 도커 허브 로그인 (비밀번호는 Secrets에서 가져옴)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HHmm
          utcOffset: "+09:00" # 한국 시간 기준

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 여기에 태그를 여러 개 적으면 도커 허브에 한 번에 여러 개가 올라갑니다!
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stagelog-repo:etl
            ${{ secrets.DOCKERHUB_USERNAME }}/stagelog-repo:etl-${{ steps.current-time.outputs.formattedTime }}